temperatures:
  - time:   00:00:00
    value:  0
  - time:   04:00:00
    value:  4
  - time:   08:00:00
    value:  8
  - time:   12:00:00
    value:  16
  - time:   16:00:00
    value:  14
  - time:   20:00:00
    value:  12
  - time:   22:00:00
    value:  8

timeStep:   1h
timeDelay:  1s
